version: '3'

services:
  weather:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 80
    ports:
      - "80:80"
    depends_on:
      - db
  events:
    build: .
    command: python app/events.py
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: example_db

networks:
  default:
    name: 'microsvcs'
    external: true