version: '3.0'

services:
  graphql:
    stdin_open: true
    build: .
    ports:
      - "4000:4000"
    volumes:
      - ./:/code
    networks:
      - microsvcs
      
networks:
  microsvcs:
    external: true