services:
  granja_service:
    build: .
    ports:
      - "5002:80"
    volumes:
      - .:/code
    links:
      - dummy_service_mongodb
  granja_service_events_receiver:
    build: .
    volumes:
      - .:/code
    links:
      - dummy_service_mongodb
    command: python3 app/events.py
  dummy_service_mongodb:
    image: mongo:5.0
    volumes:
      - dummy_service_mongodb_container:/data/db
    logging:
        driver: none

volumes:
  dummy_service_mongodb_container:

networks:
  default:
    name: microsvcs
    external: true